#request fields
geometry_msgs/PoseStamped start_pose #start pose for the planner
geometry_msgs/Vector3 start_velocity
geometry_msgs/PoseStamped goal_pose #start pose for the planner
geometry_msgs/Vector3 goal_velocity
geometry_msgs/Vector3 bounding_box
---
#response constants
uint8 PLANNINGSUCCESS=1
uint8 PLANNINGFAILED=2
#response fields
uint8 status
PlanningResponse plan

