Header header

float32     battery_voltage
string      flight_mode_ll
string      state_estimation
string      position_control
bool        serial_interface_enabled
bool        serial_interface_active
float32     flight_time
float32     cpu_load

string      motor_status

string      gps_status
int32       gps_num_satellites 

int32       debug1
int32       debug2

bool        have_SSDK_parameters

uint32      tx_packets
uint32      tx_packets_good
uint32      rx_packets
uint32      rx_packets_good

float32     timesync_offset