# This service is used to switch the flight mode.

LevelOfAutonomy request_level

---

uint8 FAILURE_UNDEFINED=0
uint8 FAILURE_LOCALIZATION_NOT_AVAILABLE=1
# ... TODO fill the failure modes in

LevelOfAutonomy resultant_level
LevelOfAutonomyChangeError[] failure_reasons # A list of reasons why the LOA change failed.
